Models/ErrorViewModel.cs
using System;

namespace CsvDlDbData.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewModels/BrandVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CsvDlDbData.ViewModels
{
    public class BrandVM
    {
        public Int64 id { get; set; }
        public string brand_name { get; set; }
        public int product_count { get; set; }
        public string image_name { get; set; }
    }
}

Controllers/BrandsController.cs
using CsvDlDbData.Repositories;
using CsvDlDbData.ViewModels;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CsvDlDbData.Controllers
{
    public class BrandsController : Controller
    {
        private readonly BrandsRepository brandsRepository;
        private readonly IDataProtector _protector;

        public BrandsController(IConfiguration configuration, IDataProtectionProvider provider)
        {
            brandsRepository = new BrandsRepository(configuration);
            _protector = provider.CreateProtector("DataProtector");
        }

        [Route("Brands/Index")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("Brands/LoadData")]
        public async Task<JsonResult> LoadData()
        {
            List<BrandVM> data = new List<BrandVM>();

            string[] columns = { "id", "brand_name" };

            int limit = Convert.ToInt32(Request.Form["length"]);
            int start = Convert.ToInt32(Request.Form["start"]);
            string draw = Request.Form["draw"];
            string dir = Request.Form["order[0][dir]"];
            string search = Request.Form["search[value]"];

            // order column names
            string order = String.Empty;
            switch (Request.Form["order[0][column]"])
            {
                case "0":
                    order = "id";
                    break;
                case "1":
                    order = "brand_name";
                    break;
                default:
                    order = "id";
                    break;

            }

            int totalRecordsCount = 0;
            int totalFilteredRecordCount = 0;

            try
            {
                totalRecordsCount = await brandsRepository.CountAllBrandsAsync();

                if (totalRecordsCount >= 0)
                {
                    totalFilteredRecordCount = totalRecordsCount;
                    data = await brandsRepository.AllBrandsAsync(start, limit, order, dir, search);

                    if (data != null)
                    {
                        if (!String.IsNullOrEmpty(search))
                        {
                            totalFilteredRecordCount = await brandsRepository.AllFilteredBrandsAsync(search);
                            if (totalRecordsCount < 0)
                            {
                                totalRecordsCount = 0;
                                totalFilteredRecordCount = 0;
                                data.Clear();
                            }
                        }

                    }
                    else
                    {
                        totalRecordsCount = 0;
                        totalFilteredRecordCount = 0;
                    }

                }

                var dataObj = new
                {
                    draw = Convert.ToInt32(draw),
                    recordsTotal = totalRecordsCount,
                    recordsFiltered = totalFilteredRecordCount,
                    data = data
                };

                return Json(dataObj);
            }
            catch (Exception)
            {
                var dataObj = new
                {
                    draw = Convert.ToInt32(draw),
                    recordsTotal = totalRecordsCount,
                    recordsFiltered = totalFilteredRecordCount,
                    data = data
                };

                return Json(dataObj);
            }

        }

        
        [Route("Brands/Download")]
        public async Task<IActionResult> Download()
        {
            var builder = new StringBuilder();
            builder.AppendLine("id,brand_name");

            try
            {

                List<BrandVM> brands = await brandsRepository.GetAllAsync();
                foreach (var item in brands)
                {
                    builder.AppendLine($"{item.id.ToString()},{item.brand_name}");
                }

                return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "brands.csv");
            }
            catch (Exception)
            {
                return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "brands.csv");
            }

        }
    }
}

Controllers/HomeController.cs
using CsvDlDbData.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CsvDlDbData.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Brands/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Brands</h1>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                Brands Listview | <a asp-controller="Brands" asp-action="Download">Download</a>
            </div>
            <div class="card-body">
                <table id="datatable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{


    <script>

        $(document).ready(function () {

            loadBrands();

        });

        function loadBrands() {

            var data = {};

            oTable = $('#datatable').DataTable({
                "processing": true,
                "serverSide": true,
                "bDestroy": true,
                "ajax": {
                    url: "/Brands/LoadData",
                    type: "post",
                    contentType: 'application/x-www-form-urlencoded',
                    data: data,
                },
                "initComplete": function () {

                    $('#tbl-datatable_filter input').unbind();

                    $('#tbl-datatable_filter input').bind('keyup', function (e) {
                        if (e.keyCode == 13) {
                            oTable.search(this.value).draw();
                        }
                    });

                },
                "columns": [
                    {
                        "data": "id"
                    },
                    {
                        "data": "brand_name"
                    }
                ]

            });

        }

        function downloadExcel() {
            var data = {}

            $.ajax({
                url: "/Brands/Download",
                type: "post",
                contentType: 'application/x-www-form-urlencoded',
                data: data,
                success: function (response) {

                    console.log(response);

                }
            });
        }

    </script>

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CsvDlDbData</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/jquery-datatable-min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CsvDlDbData</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brands" asp-action="Index">Brands</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CsvDlDbData - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-datatable-min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>